### ISSUE TITLE
Assumes git-sh-setup is in scripts working directory

### ISSUE THREAD

**Issue by goetzk** [djpohly/git-split-branch#2]
Hi,
I'm not sure which of the following is the correct fix, but the result is that running without options generates errors until git-sh-setup is linked in beside git-split-branch.

Solution one: suggest linking git-sh-setup to the scripts working directory
Solution two: document git-sh-setup/git-split-branch is supposed to be placed in a specific location (usr/libexec/git-core ? a secondary script loading location?)

I'm guessing the correct solution is number two - are you aware of a user editable location for such scripts?

thanks,

**Comment by djpohly** [comment]
Try running it as a git subcommand, i.e.:

    git split-branch yada yada

as opposed to

    git-split-branch yada yada

When run through git, it seems to set up the environment so that the Git exec path is available.

**Comment by goetzk** [comment]
Thanks for the suggestion, that gave me the push to discover what the issue was. Running via `git` does set things up correctly so I submitted a PR explaining how to install the script such that it will DTRT.

thanks,
kk
